---
- name: Install mysql server 8 and initialize
  hosts: tan-server-group
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  vars_files:
    - vars.yml

  tasks:
    # Updating the System before proceeding
    - name: Updating server
      apt:
        update_cache: yes

    # Installing the dependencies for mysql configuration
    - name: Installing apt dependencies
      apt:
        name: ['python3-pip','python3-pymysql','libmysqlclient-dev','mysql-client']

    # Installing the dependencies for mysql configuration 
    - name: "Installing pip dependencies"
      pip:
        name: ['ConfigParser']

    #MySQL server installation
    - name: Install MySQL 8.0
      action: apt pkg=mysql-server state=present
      notify: Start MySQL

    - name: Ensure mysql service is running
      systemd:
        name: mysql
        state: restarted
        enabled: yes
    
    # MySQL Configuration - Have tasks of mysql_secure_installation script in small chucks
    - name: Change the authentication plugin of MySQL root user to mysql_native_password
      shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'
    
    - name: Flush Privileges
      shell: mysql -u root -e 'FLUSH PRIVILEGES'
    
    - name: Set MySQL root password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: root
        password: "{{ mysql_root_password }}"
        check_implicit_admin: true

    - name: Add .my.cnf to user home
      template:
        src: my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600
    
    - name: Remove the test database
      mysql_db: name=test state=absent
    
    - name: Ensure anonymous users are not in the database
      mysql_user: user='' host=$item state=absent
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Creating a Dedicated MySQL User and Granting Privileges
      mysql_user: user={{mysql_user}} host="%" password={{mysql_user_password}} priv=*.*:ALL,GRANT


  #Check-point
  handlers:
    - name: Start MySQL
      service:
        name: mysql
        state: started
